name: Deploy Amazon to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./Amazon
          publish_branch: gh-pages
          personal_token: ${{ secrets.GITHUB_TOKEN }}
